### PR TITLE
Currency symbols and price amounts are now being changed in the view when the the country changes 

### LINKED ISSUE #321: Change the currency symbol and price amount on the form when a different country is selected
Check across browsers, including IE

### PR DESCRIPTION
**Pull request by ifyio**
cc/ @lc512k 
closes #321

### CODE REVIEW

**Comment by lc512k** [comment]
@ifyio I think we can remove the 'Currency has been updated to reflect the change...' div. This was put in there temporarily until we had this feature you've just added.

**Comment by lc512k** [comment]
Smoke tests fail after around 6pm when Test servers get turned off. I'm adding a workaround now so we only use prod after hours.

**Comment by lc512k** [comment]
@ifyio merged a fresh master, smoke tests are passing now

**Comment by ifyio** [comment]
@lc512k I was actually thinking that we should leave in the 'currency has been updated' messaging and even further augment it by adding the updated selected pricing information, similar to what is currently being done on ft.com.

image

I think it makes the  overall user experience much better as there will be no ambiguity about what is happening. If we remove the messaging, the user will have no idea that the pricing changed. And even if they did, to see the new pricing, they would have to scroll back up. I will be creating another issue to augment the messaging to include the pricing. For now though, I think we should leave the messaging in for the sake of transparency.

**Pull request merged**
