### PR TITLE
split out newsletter-signup

### PR DESCRIPTION
**Pull request by quarterto**
https://github.com/Financial-Times/newsletter-signup

### CODE REVIEW

**Comment by lc512k** [comment]
@ifyio @quarterto looks good, but lets make sure we have passing regression tests on a heroku branch with this code before merging to master.

**Comment by lc512k** [comment]
@quarterto I checked out this branch locally and can't submit the signup form

**Comment by quarterto** [comment]
@lc512k how do I run locally? I get `./public/main.js must exist otherwise this app will not be allowed to start` from n-express hashed-assets. How do I build that?

**Comment by lc512k** [comment]
We have smoke tests enabled now in CI, @quarteto. If you merge the latest master they will run on your branch.

Re install, build and run, we run them independently on this project.

**Pull request merged**
