### PR TITLE
Copy changes

### PR DESCRIPTION
**Pull request by ifyio**
copy changes found at https://trello.com/c/Ye3mSUzH/160-copy-changes-to-form-page

### CODE REVIEW

**Comment by lc512k** [comment]
@ifyio This will break all the annual regression tests

**Comment by ifyio** [comment]
@lc512k hmm. it passed on the branch though

**Comment by lc512k** [comment]
@ifyio the smoke tests we run per branch are only a subset of regression tests (these take 20 min and would be too much to run on every branch).

**Comment by ifyio** [comment]
Ok I have made the change here https://github.com/Financial-Times/next-signup/pull/537

**Pull request merged**
