### PR TITLE
Export dollardom

### PR DESCRIPTION
**Pull request by TheoLeanse**

### CODE REVIEW

**Comment by TheoLeanse** [comment]
@ifyio

**Comment by ifyio** [comment]
:+1:

**Comment by ifyio** [comment]
The master needs to be merged into this branch and conflicts resolved before it can be merged in

**Comment by ifyio** [comment]
Seems like there are still some files that are making reference to a global `$dom` variable. The files that are referring to the global `$dom` should all have the comment `/* globals: $dom */` at the top of the file (though it might be missing on one or two). This comment should be also removed when the file has been changed to manually import dollardom.

**Comment by commuterjoy** [comment]
this looks old, so closing. reopen if needed :)

**Pull request closed without merging**
