### PR TITLE
Allow special characters in passwords

### PR DESCRIPTION
**Pull request by lc512k**
Need to check these new characters are accepted in the password by the Subscription API?
@ifyio

### CODE REVIEW

**Comment by commuterjoy** [comment]
I wonder what the logic of this validation is? I would have thought allowing any characters of any length would be a better user experience.

**Comment by lc512k** [comment]
@commuterjoy @ifyio there was a spreadsheet with rules for all the fields, including alphanum only for passwords. I assumed these were API requirements? I'll find out

**Comment by ifyio** [comment]
@lc512k https://docs.google.com/spreadsheets/d/1cxbCifaHyyS15z8RnZKX3T7NAa9l48CensQoyIs_Mns/edit?ts=56aa5f4b#gid=0

**Comment by lc512k** [comment]
@commuterjoy do you know if janrain poses any restrictions on password characters? Otherwise it seems this is just a restriction we've carried over from the old form and could do without it.

**Comment by commuterjoy** [comment]
I think Sal would know the answer

**Comment by lc512k** [comment]
Removed all restrictions. Updated tests.

**Pull request merged**
