### PR TITLE
Running the app depends on building it first

### PR DESCRIPTION
**Pull request by quarterto**

### CODE REVIEW

**Comment by lc512k** [comment]
We usually `make build` once, then run `make run-https` as many times as we need. Forcing the build step on every `run` adds an unnecessary delay, imo. Why do you need this @quarterto?

**Comment by quarterto** [comment]
`make build` does nothing if the things it builds are up to date. I wanted to make it explicit that these are required before `run`. If you don't want to do it in the makefile, I'd suggest adding something in the readme. As someone external to the project I had to poke around to get it running.

**Comment by lc512k** [comment]
I'm trying to understand what the issue is. Doesn't every project using nbt/nht need `make install` and `make build` to be run before `make run`? I don't understand how that's different for `next-signup` or why this project's makefile would need to be different form other projects'. Can't say I've seen any that call `install` and `build` inside `run`?

One thing that *is* different about this project is that it needs to be run with `run-https` or the form won't work propperly, (which I completely agree should be in the readme), but installing and building should be fairly similar to other next projects.

**Comment by quarterto** [comment]
> Doesn't every project using nbt/nht need make install and make build to be run before make run?

I guess? I'm just speaking from my experience as a non-Next-developer unfamiliar with n-makefile.

**Comment by lc512k** [comment]
Thanks @quarterto. I'll update our Readme on how to run the project locally, we're definitely lacking there for sure. Closing this PR for now, to keep the Signup makefile consistent with the rest of next.

**Pull request closed without merging**
