### PR TITLE
Using `displayLabel` instead of `label` so as not to break the tests

### PR DESCRIPTION
**Pull request by ifyio**
cc/ @lc512k

### CODE REVIEW

**Comment by lc512k** [comment]
Instead of having yet another field in there, could we just change the selector for the tests to `annualTab: '[data-trackable="subscription-annual"]',`?

**Comment by ifyio** [comment]
@lc512k Didn't want to mess up the existing tracking data

**Comment by ifyio** [comment]
Adding an extra field is less obstructive

**Comment by lc512k** [comment]
Merged to get other branches to pass too

**Pull request merged**
